name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.XRK_SSH_HOST }}
        username: ${{ secrets.XRK_SSH_USER }}
        key: ${{ secrets.XRK_SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.XRK_SSH_PASSPHRASE }}
        rm: true
        source: "./*"
        target: "/var/www/test"